# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hiren/tspp-io/tspp-compiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hiren/tspp-io/tspp-compiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hiren/tspp-io/tspp-compiler/CMakeFiles /home/hiren/tspp-io/tspp-compiler//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hiren/tspp-io/tspp-compiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named interpreter

# Build rule for target.
interpreter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 interpreter
.PHONY : interpreter

# fast build rule for target.
interpreter/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/interpreter.dir/build.make src/CMakeFiles/interpreter.dir/build
.PHONY : interpreter/fast

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/core.dir/build.make src/CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named tokens

# Build rule for target.
tokens: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tokens
.PHONY : tokens

# fast build rule for target.
tokens/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/tokens.dir/build.make src/CMakeFiles/tokens.dir/build
.PHONY : tokens/fast

#=============================================================================
# Target rules for targets named lexer

# Build rule for target.
lexer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lexer
.PHONY : lexer

# fast build rule for target.
lexer/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/lexer.dir/build.make src/CMakeFiles/lexer.dir/build
.PHONY : lexer/fast

#=============================================================================
# Target rules for targets named parser

# Build rule for target.
parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parser
.PHONY : parser

# fast build rule for target.
parser/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/parser.dir/build.make src/CMakeFiles/parser.dir/build
.PHONY : parser/fast

#=============================================================================
# Target rules for targets named tspp_codegen

# Build rule for target.
tspp_codegen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tspp_codegen
.PHONY : tspp_codegen

# fast build rule for target.
tspp_codegen/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/tspp_codegen.dir/build.make src/CMakeFiles/tspp_codegen.dir/build
.PHONY : tspp_codegen/fast

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/intrinsics_gen.dir/build.make src/CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named vt_gen

# Build rule for target.
vt_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vt_gen
.PHONY : vt_gen

# fast build rule for target.
vt_gen/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/vt_gen.dir/build.make src/CMakeFiles/vt_gen.dir/build
.PHONY : vt_gen/fast

#=============================================================================
# Target rules for targets named omp_gen

# Build rule for target.
omp_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 omp_gen
.PHONY : omp_gen

# fast build rule for target.
omp_gen/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/omp_gen.dir/build.make src/CMakeFiles/omp_gen.dir/build
.PHONY : omp_gen/fast

#=============================================================================
# Target rules for targets named acc_gen

# Build rule for target.
acc_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acc_gen
.PHONY : acc_gen

# fast build rule for target.
acc_gen/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/acc_gen.dir/build.make src/CMakeFiles/acc_gen.dir/build
.PHONY : acc_gen/fast

#=============================================================================
# Target rules for targets named ARMTargetParserTableGen

# Build rule for target.
ARMTargetParserTableGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ARMTargetParserTableGen
.PHONY : ARMTargetParserTableGen

# fast build rule for target.
ARMTargetParserTableGen/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ARMTargetParserTableGen.dir/build.make src/CMakeFiles/ARMTargetParserTableGen.dir/build
.PHONY : ARMTargetParserTableGen/fast

#=============================================================================
# Target rules for targets named AArch64TargetParserTableGen

# Build rule for target.
AArch64TargetParserTableGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AArch64TargetParserTableGen
.PHONY : AArch64TargetParserTableGen

# fast build rule for target.
AArch64TargetParserTableGen/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/AArch64TargetParserTableGen.dir/build.make src/CMakeFiles/AArch64TargetParserTableGen.dir/build
.PHONY : AArch64TargetParserTableGen/fast

#=============================================================================
# Target rules for targets named RISCVTargetParserTableGen

# Build rule for target.
RISCVTargetParserTableGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RISCVTargetParserTableGen
.PHONY : RISCVTargetParserTableGen

# fast build rule for target.
RISCVTargetParserTableGen/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/RISCVTargetParserTableGen.dir/build.make src/CMakeFiles/RISCVTargetParserTableGen.dir/build
.PHONY : RISCVTargetParserTableGen/fast

#=============================================================================
# Target rules for targets named tspp

# Build rule for target.
tspp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tspp
.PHONY : tspp

# fast build rule for target.
tspp/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/tspp.dir/build.make src/CMakeFiles/tspp.dir/build
.PHONY : tspp/fast

#=============================================================================
# Target rules for targets named tspp_std

# Build rule for target.
tspp_std: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tspp_std
.PHONY : tspp_std

# fast build rule for target.
tspp_std/fast:
	$(MAKE) $(MAKESILENT) -f src/packages/tspp_std/CMakeFiles/tspp_std.dir/build.make src/packages/tspp_std/CMakeFiles/tspp_std.dir/build
.PHONY : tspp_std/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AArch64TargetParserTableGen"
	@echo "... ARMTargetParserTableGen"
	@echo "... RISCVTargetParserTableGen"
	@echo "... acc_gen"
	@echo "... intrinsics_gen"
	@echo "... omp_gen"
	@echo "... vt_gen"
	@echo "... core"
	@echo "... interpreter"
	@echo "... lexer"
	@echo "... parser"
	@echo "... tokens"
	@echo "... tspp"
	@echo "... tspp_codegen"
	@echo "... tspp_std"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

