# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hiren/tspp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hiren/tspp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hiren/tspp/CMakeFiles /home/hiren/tspp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hiren/tspp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tspp_interpreter

# Build rule for target.
tspp_interpreter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tspp_interpreter
.PHONY : tspp_interpreter

# fast build rule for target.
tspp_interpreter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/build
.PHONY : tspp_interpreter/fast

src/ast/ast.o: src/ast/ast.cpp.o
.PHONY : src/ast/ast.o

# target to build an object file
src/ast/ast.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/src/ast/ast.cpp.o
.PHONY : src/ast/ast.cpp.o

src/ast/ast.i: src/ast/ast.cpp.i
.PHONY : src/ast/ast.i

# target to preprocess a source file
src/ast/ast.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/src/ast/ast.cpp.i
.PHONY : src/ast/ast.cpp.i

src/ast/ast.s: src/ast/ast.cpp.s
.PHONY : src/ast/ast.s

# target to generate assembly for a file
src/ast/ast.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/src/ast/ast.cpp.s
.PHONY : src/ast/ast.cpp.s

src/common/common.o: src/common/common.cpp.o
.PHONY : src/common/common.o

# target to build an object file
src/common/common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/src/common/common.cpp.o
.PHONY : src/common/common.cpp.o

src/common/common.i: src/common/common.cpp.i
.PHONY : src/common/common.i

# target to preprocess a source file
src/common/common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/src/common/common.cpp.i
.PHONY : src/common/common.cpp.i

src/common/common.s: src/common/common.cpp.s
.PHONY : src/common/common.s

# target to generate assembly for a file
src/common/common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/src/common/common.cpp.s
.PHONY : src/common/common.cpp.s

src/interpreter/interpreter.o: src/interpreter/interpreter.cpp.o
.PHONY : src/interpreter/interpreter.o

# target to build an object file
src/interpreter/interpreter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/src/interpreter/interpreter.cpp.o
.PHONY : src/interpreter/interpreter.cpp.o

src/interpreter/interpreter.i: src/interpreter/interpreter.cpp.i
.PHONY : src/interpreter/interpreter.i

# target to preprocess a source file
src/interpreter/interpreter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/src/interpreter/interpreter.cpp.i
.PHONY : src/interpreter/interpreter.cpp.i

src/interpreter/interpreter.s: src/interpreter/interpreter.cpp.s
.PHONY : src/interpreter/interpreter.s

# target to generate assembly for a file
src/interpreter/interpreter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/src/interpreter/interpreter.cpp.s
.PHONY : src/interpreter/interpreter.cpp.s

src/lexer/lexer.o: src/lexer/lexer.cpp.o
.PHONY : src/lexer/lexer.o

# target to build an object file
src/lexer/lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/src/lexer/lexer.cpp.o
.PHONY : src/lexer/lexer.cpp.o

src/lexer/lexer.i: src/lexer/lexer.cpp.i
.PHONY : src/lexer/lexer.i

# target to preprocess a source file
src/lexer/lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/src/lexer/lexer.cpp.i
.PHONY : src/lexer/lexer.cpp.i

src/lexer/lexer.s: src/lexer/lexer.cpp.s
.PHONY : src/lexer/lexer.s

# target to generate assembly for a file
src/lexer/lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/src/lexer/lexer.cpp.s
.PHONY : src/lexer/lexer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/parser/parser.o: src/parser/parser.cpp.o
.PHONY : src/parser/parser.o

# target to build an object file
src/parser/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/src/parser/parser.cpp.o
.PHONY : src/parser/parser.cpp.o

src/parser/parser.i: src/parser/parser.cpp.i
.PHONY : src/parser/parser.i

# target to preprocess a source file
src/parser/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/src/parser/parser.cpp.i
.PHONY : src/parser/parser.cpp.i

src/parser/parser.s: src/parser/parser.cpp.s
.PHONY : src/parser/parser.s

# target to generate assembly for a file
src/parser/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/src/parser/parser.cpp.s
.PHONY : src/parser/parser.cpp.s

src/repl/repl.o: src/repl/repl.cpp.o
.PHONY : src/repl/repl.o

# target to build an object file
src/repl/repl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/src/repl/repl.cpp.o
.PHONY : src/repl/repl.cpp.o

src/repl/repl.i: src/repl/repl.cpp.i
.PHONY : src/repl/repl.i

# target to preprocess a source file
src/repl/repl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/src/repl/repl.cpp.i
.PHONY : src/repl/repl.cpp.i

src/repl/repl.s: src/repl/repl.cpp.s
.PHONY : src/repl/repl.s

# target to generate assembly for a file
src/repl/repl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/src/repl/repl.cpp.s
.PHONY : src/repl/repl.cpp.s

src/types/types.o: src/types/types.cpp.o
.PHONY : src/types/types.o

# target to build an object file
src/types/types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/src/types/types.cpp.o
.PHONY : src/types/types.cpp.o

src/types/types.i: src/types/types.cpp.i
.PHONY : src/types/types.i

# target to preprocess a source file
src/types/types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/src/types/types.cpp.i
.PHONY : src/types/types.cpp.i

src/types/types.s: src/types/types.cpp.s
.PHONY : src/types/types.s

# target to generate assembly for a file
src/types/types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tspp_interpreter.dir/build.make CMakeFiles/tspp_interpreter.dir/src/types/types.cpp.s
.PHONY : src/types/types.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tspp_interpreter"
	@echo "... src/ast/ast.o"
	@echo "... src/ast/ast.i"
	@echo "... src/ast/ast.s"
	@echo "... src/common/common.o"
	@echo "... src/common/common.i"
	@echo "... src/common/common.s"
	@echo "... src/interpreter/interpreter.o"
	@echo "... src/interpreter/interpreter.i"
	@echo "... src/interpreter/interpreter.s"
	@echo "... src/lexer/lexer.o"
	@echo "... src/lexer/lexer.i"
	@echo "... src/lexer/lexer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parser/parser.o"
	@echo "... src/parser/parser.i"
	@echo "... src/parser/parser.s"
	@echo "... src/repl/repl.o"
	@echo "... src/repl/repl.i"
	@echo "... src/repl/repl.s"
	@echo "... src/types/types.o"
	@echo "... src/types/types.i"
	@echo "... src/types/types.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

